export const SET_HOME_DATA = 'home/SET_HOME_DATA'
export const ADD_LIST_DATA = 'home/ADD_LIST_DATA'
export const CHANGE_SHOW = './home/CHANGE_SHOW'
export const SET_AUTHOR_LIST = './SET_AUTHOR_LIST'
export const SWITCH_AUTHOR_LIST = './SWITCH_AUTHOR_LIST'
export const GET_IMG_LIST = './GET_IMG_LIST'